version: "{build}"
image: Visual Studio 2015
platform:
  - x64
configuration:
  - Release

environment:
  BOOST_ROOT: C:/Libraries/boost_1_62_0
  DCMTK_ROOT: c:/Libraries/dcmtk
  ICU_ROOT: C:/Libraries/icu
  JsonCpp_ROOT: C:/Libraries/jsoncpp
  Log4Cpp_ROOT: C:/Libraries/log4cpp
  Python_ROOT: C:/Python27-x64
  VERSION: 0.7.3-1

install:
  - ps: |
      Start-FileDownload https://github.com/lamyj/appveyor-dcmtk/releases/download/v3.6.1-20161102-2/dcmtk_3.6.1-20161102-2_dynamic_x64.zip dcmtk.zip
      7z x -bd -oC:\Libraries dcmtk.zip

      Start-FileDownload http://download.icu-project.org/files/icu4c/58.2/icu4c-58_2-Win64-MSVC2015.zip
      7z x -bd -oC:\Libraries icu4c-58_2-Win64-MSVC2015.zip

      Start-FileDownload https://github.com/lamyj/appveyor-jsoncpp/releases/download/v1.8.0-2/jsoncpp_1.8.0-2_dynamic_x64.zip jsoncpp.zip
      7z x -bd -oC:\Libraries jsoncpp.zip

      Start-FileDownload https://github.com/lamyj/appveyor-log4cpp/releases/download/v1.1.1-1/log4cpp_1.1.1-dll_x64.zip log4cpp.zip
      7z x -bd -oC:\Libraries log4cpp.zip

before_build:
  - ps: |
      ${env:BUILD_DIRECTORY}="${env:APPVEYOR_BUILD_FOLDER}\build"
      ${env:INSTALL_DIRECTORY}="${env:APPVEYOR_BUILD_FOLDER}\install\${env:APPVEYOR_PROJECT_NAME}"

      New-Item -Path "${env:BUILD_DIRECTORY}" -ItemType "directory"
      cd "${env:BUILD_DIRECTORY}"

      ${generator} = "Visual Studio 14 2015"
      if (${env:PLATFORM} -eq "x64") { ${generator} = "${generator} Win64" }
      cmake `
        -G "${generator}" -DCMAKE_INSTALL_PREFIX="${env:INSTALL_DIRECTORY}" `
        -DBUILD_EXAMPLES=ON -DBUILD_WRAPPERS=ON -DUSE_BUILTIN_DCMTK_GETSCU=OFF `
        -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON -DWITH_DCMTK=ON `
        -DBOOST_LIBRARYDIR="${env:BOOST_ROOT}/lib64-msvc-14.0" `
        -DDCMTK_INCLUDE_DIR="${env:DCMTK_ROOT}/include" -DDCMTK_LIBRARY="${env:DCMTK_ROOT}/lib/dcmdata.lib" `
        -DDCMDATA_LIBRARY="${env:DCMTK_ROOT}/lib/dcmdata.lib" -DDCMNET_LIBRARY="${env:DCMTK_ROOT}/lib/dcmnet.lib" `
        -DOFLOG_LIBRARY="${env:DCMTK_ROOT}/lib/oflog.lib" -DOFSTD_LIBRARY="${env:DCMTK_ROOT}/lib/ofstd.lib" `
        -DICU_INCLUDE_DIR="${env:ICU_ROOT}/include" -DICU_LIBRARY="${env:ICU_ROOT}/lib64/icuuc.lib" `
        -DJsonCpp_INCLUDE_DIR="${env:JsonCpp_ROOT}/include" -DJsonCpp_LIBRARY="${env:JsonCpp_ROOT}/lib/jsoncpp.lib" `
        -DLog4Cpp_INCLUDE_DIR="${env:Log4Cpp_ROOT}/include" -DLog4Cpp_LIBRARY="${env:Log4Cpp_ROOT}/lib/log4cpp.lib" `
        -DPYTHON_LIBRARY="${env:Python_ROOT}/libs/python27.lib" `
        "${env:APPVEYOR_BUILD_FOLDER}"

build_script:
  - ps: |
      msbuild "${env:BUILD_DIRECTORY}\${env:APPVEYOR_PROJECT_NAME}.sln" `
        /m /clp:Verbosity=minimal /p:Configuration=${env:CONFIGURATION}
      msbuild "${env:BUILD_DIRECTORY}\INSTALL.vcxproj" `
        /m /clp:Verbosity=minimal /p:Configuration=${env:CONFIGURATION}

before_test:
  - ps: |
      & "${env:Python_ROOT}\Scripts\pip.exe" install nose

test_script:
  - ps: |
      ${env:Path} += ";${env:BOOST_ROOT}\lib64-msvc-14.0"
      ${env:Path} += ";${env:DCMTK_ROOT}\bin"
      ${env:Path} += ";${env:ICU_ROOT}\bin64"
      ${env:Path} += ";${env:JsonCpp_ROOT}\bin"
      ${env:Path} += ";${env:Log4Cpp_ROOT}\bin"
      ${env:Path} += ";${env:INSTALL_DIRECTORY}\bin"
      ${env:PYTHONPATH} = "${env:BUILD_DIRECTORY}\wrappers\${env:CONFIGURATION}"
      cd "${env:BUILD_DIRECTORY}"
      & "${env:Python_ROOT}\python.exe" ..\tests\run `
        --no-network --nose="${env:Python_ROOT}\Scripts\nosetests.exe" `
        2>&1 | % { $_.ToString() }

after_test:
  - ps: |
      Start-FileDownload https://download.microsoft.com/download/f/2/6/f263ac46-1fe9-4ae9-8fd3-21102100ebf5/msxsl.exe
      .\msxsl.exe `
        "${env:BUILD_DIRECTORY}\Testing\$(Get-Content Testing\TAG -TotalCount 1)\Test.xml" `
        "${env:APPVEYOR_BUILD_FOLDER}\ctest-to-junit.xsl" `
        -o junit.xml
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile(
        "https://ci.appveyor.com/api/testresults/xunit/${env:APPVEYOR_JOB_ID}",
        (Resolve-Path .\junit.xml))
